server:
    port: 6060
spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/ramazan
      username: postgres
      password: root
  jpa:
      show-sql: true
      format_sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2ddl:
            auto: update
          implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          jdbc:
            lob:
              non_contextual_creation: true

cache:
  expirations: 10000